### ISSUE TITLE
rd service

### ISSUE THREAD

**Issue by rohitshakya207** [jeevareddy/rdservice#3]
Unhandled Exception: MissingPluginException(No implementation found for method deviceInfo on channel msf100) #0 MethodChannel._invokeMethod

i am facing this issue in flutter app using your dependency

**Comment by rohitshakya207** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method capture on channel msf100)

**Comment by rohitshakya207** [comment]
please help me

**Comment by jeevareddy** [comment]
Hi @rohitshakya207,

Thanks for getting in touch here.

If you can provide the bellow information, it will be helpful for me to close this issue.

Device Make and Model that you are using for reading biometrics.
Device Make and Model of the Android device.
Flutter Version and Channel
Please feel free to add any information that is relevant.

Also, I am open to any collaboration on solving this issue.

Thanks.
