### ISSUE TITLE
Kotlin Version Error

### ISSUE THREAD

**Issue by DeveloperPay** [jeevareddy/rdservice#4]
I'm adding a library to my project, but I'm getting an error about Kotlin version 1.3.51 when I'm using 1.9.0.

**Comment by jeevareddy** [comment]
Hi @DeveloperPay ,

Could you please attach the exact error during the build along with Kotlin version mentioned in build.gradle?

**Comment by thedarkarchitect** [comment]
check the dependencies you using in your project if they are up to date with new standards that allow the use of new kotlin version or try a AGP assistant upgrade on your project

**Comment by thedarkarchitect** [comment]
SOLID stuff
